name: datasci
channels:
  - conda-forge
dependencies:
  - chardet=5.2.0
  - ipywidgets=8.1.1
  - jupyterlab=4.0.9
  - matplotlib-base=3.8.2
  - numpy=1.26.2
  - pandas=2.1.3
  - pip=23.3.1:
    - pytest=7.4.3
    - pytest-runner=6.0.1
    - wheel=0.42.0
    - setuptools=68.2.2
    - twine=4.0.2
  - python=3.12.0
  - scikit-learn=1.3.2=py312h6f466fd_1
  - scipy=1.11.4
  - seaborn=0.13.0
  - statsmodels=0.14.0
