name: datasci
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.0.9
  - matplotlib-base=3.8.2
  - numpy=1.26.2
  - pandas=2.1.3
  - pip=23.3.1
  - python=3.12.0
  - scikit-learn=1.3.2=py312h6f466fd_1
  - scipy=1.11.4
  - seaborn=0.13.0
  - statsmodels=0.14.0
